### ISSUE TITLE
Rule suggestie: HTTP headers must be in Hyphenated-Pascal-Case

### ISSUE THREAD

**Issue by erwinkramer** [Logius-standaarden/API-Design-Rules#196]
Suggestie:

```yaml
 casing-header-requires-hyphenated-pascal-case:
    description: HTTP headers must be in Hyphenated-Pascal-Case.
    message: HTTP header is not in Hyphenated-Pascal-Case.
    severity: warn
    given:
      - "$..parameters[?(@.in == 'header')].name"
      - "$.components.securitySchemes[?(@.in == 'header')].name"
    then:
      function: pattern
      functionOptions:
        match: "^([A-Z][a-z0-9]*)(-[A-Z][a-z0-9]*)*$"
```
