### ISSUE TITLE
Rule suggestie: Operation id's must be in PascalCase (upper camel case)

### ISSUE THREAD

**Issue by erwinkramer** [Logius-standaarden/API-Design-Rules#197]
Suggestie:

```yaml
 casing-operation-id-requires-pascal-case:
    description: Operation id's must be in PascalCase (upper camel case).
    message: Operation id is not in PascalCase.
    severity: warn
    given: "$..operationId"
    then:
      function: pattern
      functionOptions:
        match: "^[A-Z](([a-z0-9]+[A-Z]?)*)$"
```
