### ISSUE TITLE
lowerCamelCase rule `property-casing` uitbreiding suggestie

### ISSUE THREAD

**Issue by erwinkramer** [Logius-standaarden/API-Design-Rules#198]
Zie huidige `property-casing` rule: https://github.com/Logius-standaarden/API-Design-Rules/blob/fa7ea4a90366b81353101498b97b49dda42998f4/linter/spectral.yml#L148C3-L148C18

Daar kan de scope mogelijk uitgebreid worden, via:

```yaml
 casing-property-requires-camel-case:
    description: Property names, acronyms, path parameters and query parameters must be in camelCase.
    message: Property name, acronym, path parameter or query parameter is not in camelCase.
    severity: warn
    given:
      - "$..properties.*~"
      - $.paths.*.*.parameters[?(@.in=='path' || @.in=='query')].name
      - $.components.securitySchemes[?(@.in=='path' || @.in=='query')].name
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][a-z0-9]*(([A-Z]{2}|[A-Z])[a-z0-9]+)*$
```
